[package]
name = "zfs-remote-keyloader"
version = "0.1.0"
authors = ["Sam Hug <s@m-h.ug>"]
edition = "2018"

[dependencies]
clap = "2"
rocket = { features = ["tls"] }
tempfile = "3.1.0"

[build-dependencies]
bindgen = "0.51"
