[package]
name = "zfs-remote-keyloader"
version = "0.1.0"
authors = ["Sam Hug <s@m-h.ug>"]
edition = "2018"

[dependencies]
clap = "2"
futures = "0.1.29"
hyper = "0.12"
tempfile = "3.1.0"
url = "2.1.0"
