[package]
name = "zfs-remote-keyloader"
version = "0.2.5"
authors = ["Sam Hug <s@m-h.ug>"]
edition = "2021"

[dependencies]
clap = "3"
hyper = { version = "0.14", features = [ "http1", "runtime", "server"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
url = "2.2"
