[package]
name = "zfs-remote-keyloader"
version = "0.1.0"
authors = ["Sam Hug <s@m-h.ug>"]
edition = "2018"

[dependencies]
clap = "2"
futures = "0.3"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
tempfile = "3.1"
url = "2.1"
